In [25]:
import pandas as pd

## Reading the clustered document

In [35]:
df = pd.read_csv(r"dataset\output\sentences_with_hdbscan_clusters.csv")
print(df.shape)
df.head()

(116, 8)

,article_id,sentence,pub_date,emb_index,umap_x,umap_y,hdb_cluster,hdb_prob
0,184,a follow-up to xbox is expected to released at...,"Fri, 25 Mar 2022 10:33:43 GMT",87,2.547743,14.610622,2,1.000000
1,1004,a further patch fixes a hole in media player w...,"Mon, 04 Apr 2022 01:51:59 GMT",112,4.934868,15.862391,0,1.000000
2,69,according to blog analysis firm technorati the...,"Mon, 14 Mar 2022 17:55:20 GMT",35,1.029510,12.818722,3,1.000000
3,277,according to microsoft nine out of 10 xbox liv...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2.268620,14.766386,2,0.963922
4,728,according to microsoft the messages were sent ...,"Fri, 01 Apr 2022 20:58:12 GMT",93,4.430966,12.671751,-1,0.000000

In [33]:
print(f"Total columns: {len(df.columns)}")
print(f"Column names: {df.columns.tolist()}")

Total columns: 8
Column names: ['article_id', 'sentence', 'pub_date', 'emb_index', 'umap_x', 'umap_y', 'hdb_cluster', 'hdb_prob']

In [41]:
CLUSTER_NUM = 2

filtered_df = df[df['hdb_cluster']==CLUSTER_NUM]
filtered_df = filtered_df[["article_id","sentence","pub_date","hdb_cluster"]]

In [45]:
print(f"CLUSTER-{CLUSTER_NUM} Total sentences: {len(filtered_df)}")
filtered_df

CLUSTER-2 Total sentences: 22

,article_id,sentence,pub_date,hdb_cluster
0,184,a follow-up to xbox is expected to released at...,"Fri, 25 Mar 2022 10:33:43 GMT",2
3,277,according to microsoft nine out of 10 xbox liv...,"Sun, 06 Mar 2022 21:55:52 GMT",2
16,184,but in seven cases customers reported sustaini...,"Fri, 25 Mar 2022 10:33:43 GMT",2
19,184,consumers can order a new cable from the xbox ...,"Fri, 25 Mar 2022 10:33:43 GMT",2
26,277,halo 2 dropped one place to five while half-li...,"Sun, 06 Mar 2022 21:55:52 GMT",2
27,277,halo 2 has proved popular online with gamers n...,"Sun, 06 Mar 2022 21:55:52 GMT",2
28,277,halo 2 sells five million copies microsoft is ...,"Sun, 06 Mar 2022 21:55:52 GMT",2
34,184,it advised users to turn off their xboxes when...,"Fri, 25 Mar 2022 10:33:43 GMT",2
35,184,it affects xboxes made before 23 october 2003 ...,"Fri, 25 Mar 2022 10:33:43 GMT",2
40,277,its us launch was on sunday and it goes on sal...,"Sun, 06 Mar 2022 21:55:52 GMT",2
53,184,microsoft said customers would get replacement...,"Fri, 25 Mar 2022 10:33:43 GMT",2
60,277,nintendo has a 95% share of the handheld gamin...,"Sun, 06 Mar 2022 21:55:52 GMT",2
64,277,on the opening day of the world of warcraft ma...,"Sun, 06 Mar 2022 21:55:52 GMT",2
68,277,record numbers of warcraft fans are settling i...,"Sun, 06 Mar 2022 21:55:52 GMT",2
80,184,the company said the move was a preventative s...,"Fri, 25 Mar 2022 10:33:43 GMT",2
81,184,the firm said fewer than one in 10 000 console...,"Fri, 25 Mar 2022 10:33:43 GMT",2
88,277,the online game turns the stand alone warcraft...,"Sun, 06 Mar 2022 21:55:52 GMT",2
91,277,the racing game moved up one spot to first pla...,"Sun, 06 Mar 2022 21:55:52 GMT",2
92,184,the recall affects almost three quarters of al...,"Fri, 25 Mar 2022 10:33:43 GMT",2
93,277,the sequel to the best-selling need for speed:...,"Sun, 06 Mar 2022 21:55:52 GMT",2
111,184,we regret the inconvenience but believe offeri...,"Fri, 25 Mar 2022 10:33:43 GMT",2
114,184,xbox power cable fire fear microsoft has said ...,"Fri, 25 Mar 2022 10:33:43 GMT",2

## Formatting the ***pub_date*** column

In [49]:
import dateparser

In [52]:
date_col = "pub_date"

filtered_df['formated_date'] =  filtered_df[date_col].apply(
    lambda x: dateparser.parse(x, settings={
        "TIMEZONE": "UTC", 
        "RETURN_AS_TIMEZONE_AWARE": True
        })
)
filtered_df.head()

,article_id,sentence,pub_date,hdb_cluster,formated_date
0,184,a follow-up to xbox is expected to released at...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
3,277,according to microsoft nine out of 10 xbox liv...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
16,184,but in seven cases customers reported sustaini...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
19,184,consumers can order a new cable from the xbox ...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
26,277,halo 2 dropped one place to five while half-li...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00

In [55]:
sorted_df = filtered_df.sort_values(['formated_date'])
sorted_df

,article_id,sentence,pub_date,hdb_cluster,formated_date
3,277,according to microsoft nine out of 10 xbox liv...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
93,277,the sequel to the best-selling need for speed:...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
26,277,halo 2 dropped one place to five while half-li...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
27,277,halo 2 has proved popular online with gamers n...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
28,277,halo 2 sells five million copies microsoft is ...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
91,277,the racing game moved up one spot to first pla...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
88,277,the online game turns the stand alone warcraft...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
40,277,its us launch was on sunday and it goes on sal...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
60,277,nintendo has a 95% share of the handheld gamin...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
64,277,on the opening day of the world of warcraft ma...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
68,277,record numbers of warcraft fans are settling i...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2022-03-06 21:55:52+00:00
0,184,a follow-up to xbox is expected to released at...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
92,184,the recall affects almost three quarters of al...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
81,184,the firm said fewer than one in 10 000 console...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
53,184,microsoft said customers would get replacement...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
111,184,we regret the inconvenience but believe offeri...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
35,184,it affects xboxes made before 23 october 2003 ...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
34,184,it advised users to turn off their xboxes when...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
19,184,consumers can order a new cable from the xbox ...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
16,184,but in seven cases customers reported sustaini...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
80,184,the company said the move was a preventative s...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00
114,184,xbox power cable fire fear microsoft has said ...,"Fri, 25 Mar 2022 10:33:43 GMT",2,2022-03-25 10:33:43+00:00